// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_wallet.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailWallet = `-- name: CreateEmailWallet :one
INSERT INTO email_wallets (
    id, email, wallet_address, privy_user_id, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, email, wallet_address, privy_user_id, created_at, updated_at, deleted_at
`

type CreateEmailWalletParams struct {
	ID            string           `json:"id"`
	Email         string           `json:"email"`
	WalletAddress string           `json:"wallet_address"`
	PrivyUserID   string           `json:"privy_user_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) CreateEmailWallet(ctx context.Context, arg CreateEmailWalletParams) (EmailWallet, error) {
	row := q.db.QueryRow(ctx, createEmailWallet,
		arg.ID,
		arg.Email,
		arg.WalletAddress,
		arg.PrivyUserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i EmailWallet
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.WalletAddress,
		&i.PrivyUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEmailWalletByEmail = `-- name: GetEmailWalletByEmail :one
SELECT id, email, wallet_address, privy_user_id, created_at, updated_at, deleted_at FROM email_wallets
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEmailWalletByEmail(ctx context.Context, email string) (EmailWallet, error) {
	row := q.db.QueryRow(ctx, getEmailWalletByEmail, email)
	var i EmailWallet
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.WalletAddress,
		&i.PrivyUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
