// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailWallet struct {
	ID            string           `json:"id"`
	Email         string           `json:"email"`
	WalletAddress string           `json:"wallet_address"`
	PrivyUserID   string           `json:"privy_user_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}

type PaymentIntent struct {
	ID                string           `json:"id"`
	IntentID          string           `json:"intent_id"`
	PayerChain        string           `json:"payer_chain"`
	TargetChain       string           `json:"target_chain"`
	PayerWallet       pgtype.Text      `json:"payer_wallet"`
	MerchantRecipient string           `json:"merchant_recipient"`
	ReceiverEmail     pgtype.Text      `json:"receiver_email"`
	Amount            string           `json:"amount"`
	SolCommitReceipt  pgtype.Text      `json:"sol_commit_receipt"`
	SolSettleProof    pgtype.Text      `json:"sol_settle_proof"`
	SolTxHash         pgtype.Text      `json:"sol_tx_hash"`
	BaseCommitReceipt pgtype.Text      `json:"base_commit_receipt"`
	BaseSettleProof   pgtype.Text      `json:"base_settle_proof"`
	BaseTxHash        pgtype.Text      `json:"base_tx_hash"`
	Status            string           `json:"status"`
	ErrorMessage      pgtype.Text      `json:"error_message"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
	SolSettledAt      pgtype.Timestamp `json:"sol_settled_at"`
	BaseSettledAt     pgtype.Timestamp `json:"base_settled_at"`
	CompletedAt       pgtype.Timestamp `json:"completed_at"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}
