// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_intent.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentIntent = `-- name: CreatePaymentIntent :one
INSERT INTO payment_intents (
    id, intent_id, payer_chain, target_chain, merchant_recipient,
    receiver_email, amount, status, created_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, intent_id, payer_chain, target_chain, payer_wallet, merchant_recipient, receiver_email, amount, sol_commit_receipt, sol_settle_proof, sol_tx_hash, base_commit_receipt, base_settle_proof, base_tx_hash, status, error_message, created_at, expires_at, sol_settled_at, base_settled_at, completed_at, deleted_at
`

type CreatePaymentIntentParams struct {
	ID                string           `json:"id"`
	IntentID          string           `json:"intent_id"`
	PayerChain        string           `json:"payer_chain"`
	TargetChain       string           `json:"target_chain"`
	MerchantRecipient string           `json:"merchant_recipient"`
	ReceiverEmail     pgtype.Text      `json:"receiver_email"`
	Amount            string           `json:"amount"`
	Status            string           `json:"status"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	ExpiresAt         pgtype.Timestamp `json:"expires_at"`
}

func (q *Queries) CreatePaymentIntent(ctx context.Context, arg CreatePaymentIntentParams) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, createPaymentIntent,
		arg.ID,
		arg.IntentID,
		arg.PayerChain,
		arg.TargetChain,
		arg.MerchantRecipient,
		arg.ReceiverEmail,
		arg.Amount,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.PayerChain,
		&i.TargetChain,
		&i.PayerWallet,
		&i.MerchantRecipient,
		&i.ReceiverEmail,
		&i.Amount,
		&i.SolCommitReceipt,
		&i.SolSettleProof,
		&i.SolTxHash,
		&i.BaseCommitReceipt,
		&i.BaseSettleProof,
		&i.BaseTxHash,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SolSettledAt,
		&i.BaseSettledAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPaymentIntentByIntentID = `-- name: GetPaymentIntentByIntentID :one
SELECT id, intent_id, payer_chain, target_chain, payer_wallet, merchant_recipient, receiver_email, amount, sol_commit_receipt, sol_settle_proof, sol_tx_hash, base_commit_receipt, base_settle_proof, base_tx_hash, status, error_message, created_at, expires_at, sol_settled_at, base_settled_at, completed_at, deleted_at FROM payment_intents
WHERE intent_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPaymentIntentByIntentID(ctx context.Context, intentID string) (PaymentIntent, error) {
	row := q.db.QueryRow(ctx, getPaymentIntentByIntentID, intentID)
	var i PaymentIntent
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.PayerChain,
		&i.TargetChain,
		&i.PayerWallet,
		&i.MerchantRecipient,
		&i.ReceiverEmail,
		&i.Amount,
		&i.SolCommitReceipt,
		&i.SolSettleProof,
		&i.SolTxHash,
		&i.BaseCommitReceipt,
		&i.BaseSettleProof,
		&i.BaseTxHash,
		&i.Status,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.SolSettledAt,
		&i.BaseSettledAt,
		&i.CompletedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePaymentIntentBaseSettled = `-- name: UpdatePaymentIntentBaseSettled :exec
UPDATE payment_intents
SET status = $2, base_tx_hash = $3, base_settle_proof = $4, base_settled_at = $5, completed_at = $6
WHERE intent_id = $1
`

type UpdatePaymentIntentBaseSettledParams struct {
	IntentID        string           `json:"intent_id"`
	Status          string           `json:"status"`
	BaseTxHash      pgtype.Text      `json:"base_tx_hash"`
	BaseSettleProof pgtype.Text      `json:"base_settle_proof"`
	BaseSettledAt   pgtype.Timestamp `json:"base_settled_at"`
	CompletedAt     pgtype.Timestamp `json:"completed_at"`
}

func (q *Queries) UpdatePaymentIntentBaseSettled(ctx context.Context, arg UpdatePaymentIntentBaseSettledParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentBaseSettled,
		arg.IntentID,
		arg.Status,
		arg.BaseTxHash,
		arg.BaseSettleProof,
		arg.BaseSettledAt,
		arg.CompletedAt,
	)
	return err
}

const updatePaymentIntentExpired = `-- name: UpdatePaymentIntentExpired :exec
UPDATE payment_intents
SET status = 'EXPIRED'
WHERE intent_id = $1
`

func (q *Queries) UpdatePaymentIntentExpired(ctx context.Context, intentID string) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentExpired, intentID)
	return err
}

const updatePaymentIntentSolSettled = `-- name: UpdatePaymentIntentSolSettled :exec
UPDATE payment_intents
SET status = $2, amount = $3, payer_wallet = $4, sol_tx_hash = $5, sol_settled_at = $6
WHERE intent_id = $1
`

type UpdatePaymentIntentSolSettledParams struct {
	IntentID     string           `json:"intent_id"`
	Status       string           `json:"status"`
	Amount       string           `json:"amount"`
	PayerWallet  pgtype.Text      `json:"payer_wallet"`
	SolTxHash    pgtype.Text      `json:"sol_tx_hash"`
	SolSettledAt pgtype.Timestamp `json:"sol_settled_at"`
}

func (q *Queries) UpdatePaymentIntentSolSettled(ctx context.Context, arg UpdatePaymentIntentSolSettledParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentSolSettled,
		arg.IntentID,
		arg.Status,
		arg.Amount,
		arg.PayerWallet,
		arg.SolTxHash,
		arg.SolSettledAt,
	)
	return err
}

const updatePaymentIntentStatus = `-- name: UpdatePaymentIntentStatus :exec
UPDATE payment_intents
SET status = $2, error_message = $3
WHERE intent_id = $1
`

type UpdatePaymentIntentStatusParams struct {
	IntentID     string      `json:"intent_id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdatePaymentIntentStatus(ctx context.Context, arg UpdatePaymentIntentStatusParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentStatus, arg.IntentID, arg.Status, arg.ErrorMessage)
	return err
}

const updatePaymentIntentWithProof = `-- name: UpdatePaymentIntentWithProof :exec
UPDATE payment_intents
SET sol_settle_proof = $2, status = $3
WHERE intent_id = $1
`

type UpdatePaymentIntentWithProofParams struct {
	IntentID       string      `json:"intent_id"`
	SolSettleProof pgtype.Text `json:"sol_settle_proof"`
	Status         string      `json:"status"`
}

func (q *Queries) UpdatePaymentIntentWithProof(ctx context.Context, arg UpdatePaymentIntentWithProofParams) error {
	_, err := q.db.Exec(ctx, updatePaymentIntentWithProof, arg.IntentID, arg.SolSettleProof, arg.Status)
	return err
}
